---
# FILE:            {{ role_path }}/ad-hoc-alb/show-alb-hosts-facts.yml
# LICENSE:         Public Domain

# @TODO: make compatible with at least CentOS/RHEL

#    ansible-playbook ad-hoc/info/show-ufw-status.yml -i hosts
#    ansible all -a "ufw status verbose" -i hosts

- name: "ansible-ad-hoc | show-firewall-status.yml"
  hosts: all
  gather_facts: no
  tasks:
    - name: "ansible-ad-hoc | show-firewall-status.yml | sudo ufw status verbose"
      shell: "ufw status verbose"
      become: "yes"
      changed_when: false
      register: ad_hoc_alb_ufw_status_verbose

    - debug: 
        msg: "{{ ad_hoc_alb_ufw_status_verbose.stdout_lines }}"

