---

# LICENSE:         Public Domain

#    ansible-playbook install/install-benchmark-tools.yml -i hosts
#    ansible-playbook install/install-benchmark-tools.yml -i hosts --extra-vars="agree=yes extra=yes autodetect=yes"

# @TODO use pause instead of vars_prompt https://docs.ansible.com/ansible/latest/modules/pause_module.html


- name: "ansible-ad-hoc | install-benchmark-tools.yml"
  hosts: all
  gather_facts: no

  vars:

  pre_tasks:

    - name: "ansible-ad-hoc | install-benchmark-tools.yml | gather_facts minimal"
      setup:
        gather_subset:
          - "!all"

    - name: "ansible-ad-hoc | install-benchmark-tools.yml | Debian? Ubuntu?"
      fail:
        msg: "test/install-benchmark-tools.yml Tested only on Debian based distros [This host: {{ ansible_distribution }}]"
      when: "ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'"

  tasks:
